@Digitizing_HostAddress = http://localhost:5216
@Digitizing_Dapr_HostAddress = http://localhost:3506
@dapr_Api_Ver = v1.0
@stateStore = digistore
@configStore = digiconfig
@secretStore = digitizingsecrets
@pubsub = digitizingpubsub
@dapr_local_app_name= digitizer
@dapr_local_api_path = api/Name/Elaborate
@remote_app_base = http://istdapi:5142
@remote_app_path = api/Istd/Format

################# DAPR Guts

## Check and wait for side car to respond , wait for  10 secs
GET {{Digitizing_HostAddress}}/api/dapr/Sidecar/10

### Check side car health along with app health
GET {{Digitizing_HostAddress}}/api/dapr/SidecarHealth

### Check side car health only
GET {{Digitizing_HostAddress}}/api/dapr/SidecarPartialHealth

### Get configuration values using Dapr API
GET {{Digitizing_HostAddress}}/api/dapr/ConfigValues

### Get secrets from a multivalued secret store
#(local & docker, multivalue=true)
GET {{Digitizing_HostAddress}}/api/dapr/SecretValues/layered

### Set state
POST {{Digitizing_HostAddress}}/api/dapr/StateValues
Content-Type: application/json

{
  "Key": "Key1",
  "Value": "Key1-Value"
}

### Get state values
GET {{Digitizing_HostAddress}}/api/dapr/StateValues/Key1

### Call the same API Cron binding is calling 
POST {{Digitizing_HostAddress}}/api/dapr/digicron

###  remove sidecar from the pod
# DELETE {{Digitizing_HostAddress}}/api/dapr/Sidecar

### Call a non-dapr service using Dapr Http API
GET {{Digitizing_HostAddress}}/api/dapr/NonDaprEpResiliency/001

### Call a Dapr service using Dapr Http API
GET {{Digitizing_HostAddress}}/api/dapr/DaprEpResiliency/SuperWomen

### Call an endpoint that times out.
GET {{Digitizing_HostAddress}}/api/dapr/Delayed/2

### Call an endpoint that throws 500
GET {{Digitizing_HostAddress}}/api/dapr/Fault/false

###

#######################

### Convert a number to text (Calls Actors API)
POST {{Digitizing_HostAddress}}/api/name/NumberToText/0014695762345

### A Post API To convert number to text
POST {{Digitizing_HostAddress}}/api/name/Result
Content-Type: application/json

{
  "Nr":"9725689875",
  "CountryCode": "001"
}

###  Convert a 10 digit text to number, Using DaprClient for Service integration
GET {{Digitizing_HostAddress}}/api/name/TextToNumber/001MyNameYati

### Call a pubsub api
GET {{Digitizing_HostAddress}}/api/name/Digitize/001MyNameYati

### Calls Spelling Alphabets
GET {{Digitizing_HostAddress}}/api/name/Elaborate/string

### Health check on the API
GET {{Digitizing_HostAddress}}/health

###
######################### Calls Dapr components directly, works in non-k8s env.
POST {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/state/{{stateStore}}
Content-Type: application/json

[
    {
        "key": "state",
        "value": "Gotham"
    },
    {
        "key": "Name",
        "value": "Bruce Wayne"
    },
    {
        "key": "Aka",
        "value": "Batman"
    }
]

###
GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/state/{{stateStore}}/state
###

DELETE {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/state/{{stateStore}}/state

###
GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/secrets/{{secretStore}}/layered
### (MultiValue=true) Only valid for local/docker deployment!
GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/secrets/{{secretStore}}/layered

### K8s (MultiValue=false) only valid for K8s deployment###
GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/secrets/digitizing-secrets/digitizingsecrets

###
POST {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/publish/{{pubsub}}/result?metadata.rawPayload=false
Content-Type: application/json

{
    "Nr":"3451236789",
    "CountryCode":"001"
}

###
GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/configuration/{{configStore}}?key=configKey1
###
GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/invoke/{{dapr_local_app_name}}/method/{{dapr_local_api_path}}/Myname

###
GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/invoke/{{remote_app_base}}/method/{{remote_app_path}}/001

###
GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/healthz
###

GET {{Digitizing_Dapr_HostAddress}}/{{dapr_Api_Ver}}/metadata
###
GET http://localhost:8080/placement/state