apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: digiconfig
spec:
  type: configuration.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    secretKeyRef:
      name: redisPass
      key: redisPass      
auth:
  secretStore: compsecrets

