apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: digicron
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 10s" # valid cron schedule
  - name: direction
    value: "input" # direction of the cron binding
