kind: PersistentVolume
apiVersion: v1
metadata:
  name: config-volume-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/resource'
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
