
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: digitizing-secrets   # this is secret store name
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - name: ""