apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: digitizerresiliency
spec:
  policies:
    timeouts:
      general: 4s
      important: 20s
      largeResponse: 25s
    retries:
      retryLimited:
        policy: constant
        maxInterval: 3s
        maxRetries: 4
    circuitBreakers:
      simpleCB:
        maxRequests: 1
        interval: 120s
        timeout: 40s 
        trip: consecutiveFailures >= 3

  targets:
    apps:
      digitsworker:
        timeout: important
        retry: retryLimited
        circuitBreaker: simpleCB
      istdapi:
        timeout: important
        retry: retryLimited
        circuitBreaker: simpleCB
    components:
      statestore:
        outbound:
          retry: retryLimited
          circuitBreaker: simpleCB
scopes:
  - digitizer
  - digitsworker