apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: digitizerresiliency
spec:
  policies:
    retries:
      retryForever:
        policy: constant
        maxInterval: 5s
        maxRetries: -1 
    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s 
        trip: consecutiveFailures >= 5

  targets:
    apps:
      digitsworker:
        retry: retryForever
        circuitBreaker: simpleCB
    components:
      statestore:
        outbound:
          retry: retryForever
          circuitBreaker: simpleCB

scopes:
  - digitizer
